"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type View = "dashboard" | "subjects" | "detail";
type Filter = "Todas" | "Frontend" | "Backend" | "Banco de Dados" | "DevOps" | "Outros";
type ContentFilter = "Todos" | "Concluídos" | "Pendentes";

type Content = { id: string; name: string; completed: boolean; completedAt?: string };
type Subject = { id: string; name: string; description: string; category: string; icon: string; color: string; contents: Content[] };

const STORAGE_KEY = "study-hub-subjects";
const seedSubjects: Subject[] = [
  { id: "frontend", name: "Frontend", description: "Interfaces que combinam clareza, código e experiência.", category: "Frontend", icon: "◒", color: "coral", contents: [{ id: "html", name: "HTML semântico", completed: true, completedAt: "2026-08-17" }, { id: "css", name: "CSS moderno", completed: true, completedAt: "2026-08-15" }, { id: "js", name: "JavaScript", completed: false }, { id: "react", name: "React e componentes", completed: false }, { id: "next", name: "Next.js App Router", completed: false }] },
  { id: "backend", name: "Backend", description: "Serviços robustos para fazer produtos acontecerem.", category: "Backend", icon: "⌁", color: "blue", contents: [{ id: "http", name: "HTTP e APIs", completed: true, completedAt: "2026-08-12" }, { id: "node", name: "Node.js", completed: true, completedAt: "2026-08-10" }, { id: "auth", name: "Autenticação", completed: false }, { id: "tests", name: "Testes de integração", completed: false }] },
  { id: "database", name: "Banco de Dados", description: "Dados bem modelados são decisões mais rápidas.", category: "Banco de Dados", icon: "◫", color: "mint", contents: [{ id: "sql", name: "SQL essencial", completed: true, completedAt: "2026-08-08" }, { id: "modeling", name: "Modelagem relacional", completed: false }, { id: "indexes", name: "Índices e performance", completed: false }] },
  { id: "devops", name: "DevOps", description: "Automação, observabilidade e entregas tranquilas.", category: "DevOps", icon: "↗", color: "yellow", contents: [{ id: "git", name: "Git e branches", completed: true, completedAt: "2026-08-05" }, { id: "ci", name: "CI/CD", completed: false }, { id: "deploy", name: "Deploy", completed: false }] },
];

const today = () => new Date().toISOString().slice(0, 10);
const progress = (subject: Subject) => subject.contents.length ? Math.round(subject.contents.filter((item) => item.completed).length / subject.contents.length * 100) : 0;

export default function StudyHub({ view, subjectId }: { view: View; subjectId?: string }) {
  const [subjects, setSubjects] = useState<Subject[]>(seedSubjects);
  const [ready, setReady] = useState(false);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState<Filter>("Todas");
  const [contentFilter, setContentFilter] = useState<ContentFilter>("Todos");
  const [modal, setModal] = useState<"subject" | "content" | null>(null);
  const [editingSubject, setEditingSubject] = useState<Subject | null>(null);
  const [editingContent, setEditingContent] = useState<Content | null>(null);

  useEffect(() => {
    const frame = window.requestAnimationFrame(() => {
      const saved = window.localStorage.getItem(STORAGE_KEY);
      if (saved) {
        try { setSubjects(JSON.parse(saved) as Subject[]); } catch { window.localStorage.removeItem(STORAGE_KEY); }
      }
      setReady(true);
    });
    return () => window.cancelAnimationFrame(frame);
  }, []);

  useEffect(() => { if (ready) window.localStorage.setItem(STORAGE_KEY, JSON.stringify(subjects)); }, [subjects, ready]);

  const updateSubjects = (updater: (current: Subject[]) => Subject[]) => setSubjects((current) => updater(current));
  const selected = subjects.find((subject) => subject.id === subjectId);
  const totals = useMemo(() => ({ contents: subjects.reduce((total, subject) => total + subject.contents.length, 0), completed: subjects.reduce((total, subject) => total + subject.contents.filter((item) => item.completed).length, 0) }), [subjects]);
  const overall = totals.contents ? Math.round(totals.completed / totals.contents * 100) : 0;
  const visibleSubjects = subjects.filter((subject) => (category === "Todas" || (category === "Outros" ? !["Frontend", "Backend", "Banco de Dados", "DevOps"].includes(subject.category) : subject.category === category)) && subject.name.toLowerCase().includes(query.toLowerCase()));
  const visibleContents = selected?.contents.filter((item) => item.name.toLowerCase().includes(query.toLowerCase()) && (contentFilter === "Todos" || (contentFilter === "Concluídos" ? item.completed : !item.completed))) ?? [];

  function removeSubject(subject: Subject) {
    if (window.confirm(`Excluir a matéria "${subject.name}" e todos os seus conteúdos?`)) updateSubjects((items) => items.filter((item) => item.id !== subject.id));
  }
  function resetData() { if (window.confirm("Restaurar as matérias de exemplo? Isso substitui seus dados atuais.")) setSubjects(seedSubjects); }

  if (view === "detail" && !selected) return <Shell><EmptyState title="Matéria não encontrada" text="Essa matéria pode ter sido removida ou o endereço está incorreto." action={<Link className="button primary" href="/subjects">Voltar para matérias</Link>} /></Shell>;

  return <Shell>
    {view === "dashboard" && <Dashboard subjects={subjects} overall={overall} totals={totals} />}
    {view === "subjects" && <><PageHeading eyebrow="Biblioteca" title="Suas matérias" text="Organize o que você quer aprender em pequenos passos." action={<div className="heading-actions"><button className="button ghost" onClick={resetData}>Restaurar exemplos</button><button className="button primary" onClick={() => { setEditingSubject(null); setModal("subject"); }}>+ Nova matéria</button></div>} /><div className="toolbar"><input aria-label="Pesquisar matérias" className="search" placeholder="Pesquisar matérias..." value={query} onChange={(event) => setQuery(event.target.value)} /><div className="filters">{(["Todas", "Frontend", "Backend", "Banco de Dados", "DevOps", "Outros"] as Filter[]).map((item) => <button className={category === item ? "filter active" : "filter"} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div></div>{visibleSubjects.length ? <div className="subject-grid">{visibleSubjects.map((subject) => <SubjectCard key={subject.id} subject={subject} onEdit={() => { setEditingSubject(subject); setModal("subject"); }} onDelete={() => removeSubject(subject)} />)}</div> : <EmptyState title="Nenhuma matéria encontrada" text="Tente outra busca ou comece adicionando uma matéria." />}</>}
    {view === "detail" && selected && <Detail subject={selected} query={query} setQuery={setQuery} contentFilter={contentFilter} setContentFilter={setContentFilter} contents={visibleContents} onAdd={() => { setEditingContent(null); setModal("content"); }} onToggle={(content) => updateSubjects((items) => items.map((item) => item.id === selected.id ? { ...item, contents: item.contents.map((entry) => entry.id === content.id ? { ...entry, completed: !entry.completed, completedAt: !entry.completed ? today() : undefined } : entry) } : item))} onEdit={(content) => { setEditingContent(content); setModal("content"); }} onDelete={(content) => updateSubjects((items) => items.map((item) => item.id === selected.id ? { ...item, contents: item.contents.filter((entry) => entry.id !== content.id) } : item))} onEditSubject={() => { setEditingSubject(selected); setModal("subject"); }} onDeleteSubject={() => removeSubject(selected)} />}
    {modal === "subject" && <SubjectForm subject={editingSubject} onClose={() => setModal(null)} onSave={(data) => { updateSubjects((items) => editingSubject ? items.map((item) => item.id === editingSubject.id ? { ...item, ...data } : item) : [...items, { ...data, id: `${Date.now()}`, color: ["coral", "blue", "mint", "yellow"][items.length % 4], contents: [] }]); setModal(null); }} />}
    {modal === "content" && selected && <ContentForm content={editingContent} existing={selected.contents} onClose={() => setModal(null)} onSave={(data) => { updateSubjects((items) => items.map((item) => item.id === selected.id ? { ...item, contents: editingContent ? item.contents.map((entry) => entry.id === editingContent.id ? { ...entry, name: data.name } : entry) : [...item.contents, { id: `${Date.now()}`, name: data.name, completed: false }] } : item)); setModal(null); }} />}
  </Shell>;
}

function Shell({ children }: { children: React.ReactNode }) { return <div className="app-shell"><aside className="sidebar"><Link href="/" className="brand"><span className="brand-mark">S</span><span>Study <b>Hub</b></span></Link><p className="nav-label">Workspace</p><nav><Link href="/" className="nav-link"><span>⌂</span>Dashboard</Link><Link href="/subjects" className="nav-link"><span>▦</span>Matérias</Link></nav><div className="sidebar-note"><span className="spark">✦</span><strong>Um pouco por dia.</strong><p>Constância transforma curiosidade em domínio.</p></div><div className="sidebar-footer"><span className="avatar">JS</span><div><strong>João estudante</strong><small>Plano pessoal</small></div></div></aside><main className="main-content"><header className="topbar"><span className="mobile-brand">Study <b>Hub</b></span><span className="topbar-date">Quarta, 19 de agosto de 2026</span><div className="top-actions"><button className="icon-button" aria-label="Notificações">♢</button><span className="avatar">JS</span></div></header>{children}</main></div>; }
function PageHeading({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: React.ReactNode }) { return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="heading-text">{text}</p></div>{action}</div>; }
function ProgressBar({ value }: { value: number }) { return <div className="progress-track"><span style={{ width: `${value}%` }} /></div>; }
function Dashboard({ subjects, overall, totals }: { subjects: Subject[]; overall: number; totals: { contents: number; completed: number } }) { const recent = subjects.flatMap((subject) => subject.contents.filter((item) => item.completed).map((item) => ({ ...item, subject }))).sort((a, b) => (b.completedAt ?? "").localeCompare(a.completedAt ?? "")).slice(0, 4); return <><PageHeading eyebrow="Visão geral" title="Olá, estudante!" text="Seu espaço para aprender com intenção e acompanhar cada avanço." action={<Link className="button ghost" href="/subjects">Ver matérias <span>↗</span></Link>} /><section className="stats"><Stat value={subjects.length} label="Matérias ativas" icon="▦" tone="coral" /><Stat value={totals.contents} label="Conteúdos" icon="◌" tone="blue" /><Stat value={totals.completed} label="Concluídos" icon="✓" tone="mint" /><Stat value={`${overall}%`} label="Progresso geral" icon="◔" tone="yellow" /></section><section className="section-block"><div className="section-title"><div><p className="eyebrow">Seu próximo passo</p><h2>Continue estudando</h2></div><Link href="/subjects" className="text-link">Ver todas ↗</Link></div><div className="continue-grid">{subjects.slice(0, 3).map((subject) => <Link href={`/subjects/${subject.id}`} className="continue-card" key={subject.id}><span className={`subject-icon ${subject.color}`}>{subject.icon}</span><span className="card-kicker">{subject.category}</span><h3>{subject.name}</h3><div className="card-meta"><span>{subject.contents.filter((item) => item.completed).length} de {subject.contents.length}</span><strong>{progress(subject)}%</strong></div><ProgressBar value={progress(subject)} /></Link>)}</div></section><section className="section-block activity-section"><div className="section-title"><div><p className="eyebrow">Ritmo de aprendizado</p><h2>Atividade recente</h2></div><span className="activity-count">{recent.length} atualizações</span></div><div className="activity-list">{recent.length ? recent.map((item) => <div className="activity-item" key={`${item.subject.id}-${item.id}`}><span className="check-dot">✓</span><div><strong>{item.name}</strong><p>{item.subject.name}</p></div><time>{item.completedAt}</time></div>) : <EmptyState title="Ainda não há atividade" text="Conclua um conteúdo para vê-lo aqui." />}</div></section></>; }
function Stat({ value, label, icon, tone }: { value: string | number; label: string; icon: string; tone: string }) { return <div className="stat-card"><span className={`stat-icon ${tone}`}>{icon}</span><div><strong>{value}</strong><span>{label}</span></div></div>; }
function SubjectCard({ subject, onEdit, onDelete }: { subject: Subject; onEdit: () => void; onDelete: () => void }) { return <article className="subject-card"><div className="subject-card-top"><span className={`subject-icon ${subject.color}`}>{subject.icon}</span><div className="card-actions"><button aria-label={`Editar ${subject.name}`} onClick={onEdit}>✎</button><button aria-label={`Excluir ${subject.name}`} onClick={onDelete}>×</button></div></div><span className="card-kicker">{subject.category}</span><h2>{subject.name}</h2><p>{subject.description}</p><div className="card-meta"><span>{subject.contents.length} conteúdos</span><strong>{progress(subject)}%</strong></div><ProgressBar value={progress(subject)} /><Link className="button outline full" href={`/subjects/${subject.id}`}>Acessar matéria <span>↗</span></Link></article>; }
function Detail({ subject, query, setQuery, contentFilter, setContentFilter, contents, onAdd, onToggle, onEdit, onDelete, onEditSubject, onDeleteSubject }: { subject: Subject; query: string; setQuery: (value: string) => void; contentFilter: ContentFilter; setContentFilter: (value: ContentFilter) => void; contents: Content[]; onAdd: () => void; onToggle: (content: Content) => void; onEdit: (content: Content) => void; onDelete: (content: Content) => void; onEditSubject: () => void; onDeleteSubject: () => void }) { return <><Link href="/subjects" className="back-link">← Voltar para matérias</Link><div className="detail-hero"><div><span className={`subject-icon large ${subject.color}`}>{subject.icon}</span><p className="eyebrow">{subject.category}</p><h1>{subject.name}</h1><p className="heading-text">{subject.description}</p></div><div className="detail-actions"><button className="button ghost" onClick={onEditSubject}>Editar</button><button className="button danger-ghost" onClick={onDeleteSubject}>Excluir</button></div></div><div className="detail-stats"><div><strong>{progress(subject)}%</strong><span>progresso</span></div><div><strong>{subject.contents.length}</strong><span>conteúdos</span></div><div><strong>{subject.contents.filter((item) => item.completed).length}</strong><span>concluídos</span></div><div className="detail-progress"><ProgressBar value={progress(subject)} /><small>{subject.contents.filter((item) => item.completed).length} de {subject.contents.length} conteúdos concluídos</small></div></div><div className="content-heading"><div><p className="eyebrow">Plano de estudos</p><h2>Conteúdos</h2></div><button className="button primary" onClick={onAdd}>+ Adicionar conteúdo</button></div><div className="toolbar content-toolbar"><input aria-label="Pesquisar conteúdos" className="search" placeholder="Pesquisar conteúdos..." value={query} onChange={(event) => setQuery(event.target.value)} /><div className="filters">{(["Todos", "Concluídos", "Pendentes"] as ContentFilter[]).map((item) => <button className={contentFilter === item ? "filter active" : "filter"} key={item} onClick={() => setContentFilter(item)}>{item}</button>)}</div></div><div className="content-list">{contents.length ? contents.map((content) => <div className={`content-item ${content.completed ? "done" : ""}`} key={content.id}><button className="content-check" aria-label={content.completed ? `Desmarcar ${content.name}` : `Concluir ${content.name}`} onClick={() => onToggle(content)}>{content.completed ? "✓" : ""}</button><div><strong>{content.name}</strong><span>{content.completed ? `Concluído em ${content.completedAt}` : "Pendente"}</span></div><div className="content-actions"><button aria-label={`Editar ${content.name}`} onClick={() => onEdit(content)}>✎</button><button aria-label={`Excluir ${content.name}`} onClick={() => onDelete(content)}>×</button></div></div>) : <EmptyState title="Nenhum conteúdo encontrado" text="Ajuste a busca ou adicione um novo conteúdo." />}</div></>; }
function EmptyState({ title, text, action }: { title: string; text: string; action?: React.ReactNode }) { return <div className="empty-state"><span>◌</span><h3>{title}</h3><p>{text}</p>{action}</div>; }
function SubjectForm({ subject, onClose, onSave }: { subject: Subject | null; onClose: () => void; onSave: (data: Pick<Subject, "name" | "description" | "category" | "icon">) => void }) { const [name, setName] = useState(subject?.name ?? ""); const [description, setDescription] = useState(subject?.description ?? ""); const [category, setCategory] = useState(subject?.category ?? "Frontend"); const [icon, setIcon] = useState(subject?.icon ?? "◒"); const submit = (event: FormEvent) => { event.preventDefault(); if (name.trim()) onSave({ name: name.trim(), description: description.trim(), category, icon }); }; return <Modal title={subject ? "Editar matéria" : "Nova matéria"} onClose={onClose}><form onSubmit={submit}><label>Nome<input autoFocus required value={name} onChange={(event) => setName(event.target.value)} placeholder="Ex: Design de produto" /></label><label>Descrição<input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="O que você quer dominar?" /></label><label>Categoria<select value={category} onChange={(event) => setCategory(event.target.value)}><option>Frontend</option><option>Backend</option><option>Banco de Dados</option><option>DevOps</option><option>Outros</option></select></label><label>Ícone<input value={icon} onChange={(event) => setIcon(event.target.value)} maxLength={2} /></label><div className="form-actions"><button type="button" className="button ghost" onClick={onClose}>Cancelar</button><button className="button primary">Salvar matéria</button></div></form></Modal>; }
function ContentForm({ content, existing, onClose, onSave }: { content: Content | null; existing: Content[]; onClose: () => void; onSave: (data: { name: string }) => void }) { const [name, setName] = useState(content?.name ?? ""); const [error, setError] = useState(""); const submit = (event: FormEvent) => { event.preventDefault(); const clean = name.trim(); if (!clean) return; if (!content && existing.some((item) => item.name.toLowerCase() === clean.toLowerCase())) { setError("Esse conteúdo já existe nesta matéria."); return; } onSave({ name: clean }); }; return <Modal title={content ? "Editar conteúdo" : "Adicionar conteúdo"} onClose={onClose}><form onSubmit={submit}><label>Nome do conteúdo<input autoFocus required value={name} onChange={(event) => { setName(event.target.value); setError(""); }} placeholder="Ex: Componentes reutilizáveis" /></label>{error && <p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="button ghost" onClick={onClose}>Cancelar</button><button className="button primary">Salvar conteúdo</button></div></form></Modal>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="modal"><div className="modal-header"><h2>{title}</h2><button aria-label="Fechar" onClick={onClose}>×</button></div>{children}</div></div>; }